services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./redis:/data:Z

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "${PAPERLESS_PORT:-8000}:${PAPERLESS_PORT:-8000}"
    volumes:
      - ./data:/usr/src/paperless/data:Z
      - ./media:/usr/src/paperless/media:Z
      - ./export:/usr/src/paperless/export:Z,U
      - ./consume:/usr/src/paperless/consume:Z,U
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIME_ZONE: UTC
      PAPERLESS_OCR_LANGUAGE: por+spa+eng
      PAPERLESS_OCR_LANGUAGES: por spa eng
